// Ganti dengan URL dan Anon Key dari Project Supabase Anda
const SUPABASE_URL = 'https://wlxlyxbigtrgzdknutkw.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndseGx5eGJpZ3RyZ3pka251dGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUzODQ2NzQsImV4cCI6MjEwMDk2MDY3NH0.nr6Tf48PmWT8V7I8glKbSBXVfm6xg8jy0G6I_fN1YjM';
